### ISSUE TITLE
Doesn't work as it should

### ISSUE THREAD

**Issue by jduffas** [chemistorge/Arduino-Motorised-Filter-Wheel-Xagyl-compatible-ASCOM-and-INDI-#2]
In fact it does.
Juste a resistor problem.

I would like to delete this comment, but I can't.

**Comment by jduffas** [comment]
I understant a little bit more, I added comments in tu program, I see that it thinks all the time it found the magnet...
so, the sensor is a A3144 only.
Do I have to add a 10K resistor?
is it an analog sensor?
if it's digital, is it a high or low?
when setting to High, I fails to home, is all other cases, it says it goes to home, but in fact it doesn't : it detect magnet every time, even when there isn't one.

**Comment by chemistorge** [comment]
I have rewrote the home code as it was a complete mess, it will now identify sensor type and if analog the threshold value.

**Comment by chemistorge** [comment]
Hi,
You need a 10k resister as a pull up from the signal to 5v for the 3144,
analogue sensors do not. In the absence of a magnetic field an analogue
sensor will read around 512 using analog read where as a digital will be
either 0 or 1023.

Check out my updated homing code to see how I can detect the type of sensor.

Regards

Mark

**Comment by jduffas** [comment]
Hello, 
Thank you for your answer,
I noticed I needed a 10 K resistor.
Now it's working fine, thank you :-)
